### ISSUE TITLE
Problem making deposits

### ISSUE THREAD

**Issue by litch** [juancgarza/Account-Api-Example#3]
Having used a different route than what was requested in the design specification `/api/accounts` rather than just `/accounts`, I tried to make a deposit to an account I had created:

```
% curl -H "Content-Type: application/json" -X POST -d '{"amount":1}' localhost:3000/api/accounts/1/deposit

{"transaction":{"errors":{"amount":["must be an integer"]}}}%
```

**Comment by juancgarza** [comment]
Changed float to integer in transaction.amount model ... also changed routing and controller so that it could run un localhost:3000/accounts/1/deposit
